CREATE TABLE ADVENTURE_TRIP (
    TRIP_ID DECIMAL(3, 0) PRIMARY KEY,
    TRIP_NAME VARCHAR(75),
    START_LOCATION CHAR(50),
    STATE CHAR(2),
    DISTANCE NUMBER,
    MAX_GRP_SIZE NUMBER
);

INSERT INTO ADVENTURE_TRIP (TRIP_ID, TRIP_NAME, START_LOCATION, STATE, DISTANCE, MAX_GRP_SIZE)
VALUES (45, 'Jay Peak', 'Jay', 'VT', 8, 5);

DROP TABLE ADVENTURE_TRIP;